### ISSUE TITLE
{ media_count: 13997048, name: 'blue' }... 

### ISSUE THREAD

**Issue by alexiskattan** [mckelvey/instagram-node-lib#17]
I am doing this search

```
Instagram.tags.search
    q: 'blue'
    complete: (data)->
       console.log data
```

This returns `{ media_count: 13997048, name: 'blue' }`

But how do I go from the `{ media_count: 13997048, name: 'blue' }` to the actual images?

**Comment by mckelvey** [comment]
`Instagram.tags.search` corresponds to searching for a tag when you are unsure of a matching tag existing, so you get back the matching tags, along with their media count or how often they’ve been applied to media.

Once you know that “blue” is a valid tag, you can then use `Instagram.tags.recent` to get the media that has most recently had the tag applied to them. Make sense?
