### ISSUE TITLE
How do you use this on localhost? I get cors issues.

### ISSUE THREAD

**Issue by rublev** [mckelvey/instagram-node-lib#46]
I get the following error in my console on `localhost` when trying to get data for my user `Instagram.users.self()`:

![image](https://user-images.githubusercontent.com/470273/27408193-823808a4-56a9-11e7-85ca-11abeff1cc30.png)

**Comment by michaeleekk** [comment]
I think this library is supposed to run on the nodejs side instead of in the browser.
I found this one for browser quite nice: https://github.com/stevenschobert/instafeed.js

**Comment by mckelvey** [comment]
Thanks @michaeleekk — yes indeed, instagram-node-lib is designed to be used with node.js in a server environment.
