### ISSUE TITLE
Missing req.rawBody for Instagram.subscriptions.verified(req)

### ISSUE THREAD

**Issue by PatrickHeneise** [mckelvey/instagram-node-lib#6]
The new version of express/connect doesn't support rawBody any more. What's the best way to get the raw body and verify it?

TypeError: Not a string or buffer
    at InstagramSubscriptions.verified (/data/apps/abc/node_modules/instagram-node-lib/lib/class.instagram.subscriptions.js:44:12)
    at instagram.js:9:39

**Comment by mckelvey** [comment]
Thanks Patrick — I’ll take a look and see what other options might exist. Until then you might stay on express 2.x; 3.0 is still in beta (but like you, I’ve also ended up with it loaded too).

**Comment by PatrickHeneise** [comment]
I tried something like this before bodyParser():

```
app.use(function(req, res, next) {
  if (0 == req.url.indexOf('/api')) {
    console.log('setting rawBody');
    var data='';
    req.setEncoding('utf8');

    req.on('data', function(chunk) { 
      data += chunk;
    });

    req.on('end', function() {
      console.log('data: ', data);
      req.rawBody = data;
      next();
    });
  } else {
    next();
  }
});
```

But that didn't work properly.

**Comment by mckelvey** [comment]
@PatrickHeneise — I’ve been looking into this but can’t replicate in my tests yet. Tell me, [does this comment](https://github.com/visionmedia/express/issues/897#issuecomment-3314823) help?

**Comment by PatrickHeneise** [comment]
The posted middleware is pretty much the same as in the comment and doesn't work.

The question is related to Instagram.subscriptions.verified(req), which checks req.rawBody for the HMAC response from Instagram to verify the data is really coming from Instagram. As said, it just doesn't work with Express >3.0 any more.

app.get('/api/instagram/callback', function(req, res) {
  Instagram.subscriptions.handshake(req, res);
});

app.post('/api/instagram/callback', function(req, res){
  console.log(Instagram.subscriptions.verified(req));
});

This minimum example should throw an error already when an Instagram callback comes in.

**Comment by nathanbowser** [comment]
I looked into this a bit.  I have this module working with express3 and subscription updates.  I'm not calling Instagram.subscriptions.verified(req) and just handling things myself.

**Comment by mckelvey** [comment]
@nathanbowser I’ll be looking at making a fix over the weekend, if you wouldn’t mind sharing your solution I’ll see if I can work it in to fix verify.

**Comment by nathanbowser** [comment]
I didn't look into it deep enough to figure out why you need to call that verify function. If you simply fire a res.json {ok: true} or res.send 'Alive and well', I think that''s enough to make their API happy. Do that right away, though. In your POST callback, fire an async function to process the request and go get the actual data. Then return a status okay message.

**Comment by mckelvey** [comment]
Gotcha — I admit the risk that someone else would ping your callback address is minimal, so bypassing the check is a reasonable option. I’ll still dig on the weekend to see if I can get to the raw response. :)

**Comment by PatrickHeneise** [comment]
@nathanbowser you need to send the handshake to Instagram to verify your server and you can verify the response with the verify function. The risk is indeed low, but it's a direct link into the system and should be verified, I think. At the moment I'm just not verifying and everything is fine but for production use I'd prefer to do that.

**Comment by PatrickHeneise** [comment]
I tried several things to get to the rawBody without success so far. I guess the middleware is the only solution. I'll try that again later.

**Comment by mckelvey** [comment]
@PatrickHeneise let me know if you make any headway. My next plan is to see if I could take the callback out of Express’s handling and use connect directly to get the raw content if I can’t get Express to save a copy.
