### ISSUE TITLE
User info requires access_token

### ISSUE THREAD

**Issue by scttnlsn** [mckelvey/instagram-node-lib#8]
I am getting an "Error: APINotAllowedError: you cannot view this resource" when requesting user info.  When I monkey patch the info function to include the access_token things seem to work fine.

``` javascript
Instagram.users.info = function(params) {
  var credentials;
  credentials = this.parent._credentials(params, 'access_token');
  params['path'] = "/" + this.parent._api_version + "/users/" + params['user_id'] + "?" + (this.parent._to_querystring(credentials));
  return this.parent._request(params);
};
```

http://instagram.com/developer/endpoints/users/#get_users

**Comment by dbrand666** [comment]
I'm seeing the same here.  Is there any reason the param handling for these 2 methods is special?

  info: (params) ->
    credentials = @parent._credentials {}
    params['path'] = "/#{@parent._api_version}/users/#{params['user_id']}?#{@parent._to_querystring(credentials)}"
    @parent._request params

  search: (params) ->
    params = @parent._credentials params
    params['path'] = "/#{@parent._api_version}/users/search?#{@parent._to_querystring(params)}"
    @parent._request params

Changing then to:

  info: (params) ->
    params = @parent._credentials params, 'access_token'
    params['path'] = "/#{@parent._api_version}/users/#{params['user_id']}?#{@parent._to_querystring(params)}"
    @parent._request params

  search: (params) ->
    params = @parent._credentials params, 'access_token'
    params['path'] = "/#{@parent._api_version}/users/search?#{@parent._to_querystring(params)}"
    @parent._request params

... would seem to do the trick.

**Comment by mckelvey** [comment]
Thanks guys — pull request merged. :)

**Comment by dbrand666** [comment]
Thanks!  I really appreciate your hard work and how quickly you turned 
this around.

Can you push this change to npm?

**Comment by mckelvey** [comment]
Thanks for the reminder — done — v 0.1.1.
